version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    ports:
      - "${WEBSERVER_PORT}:80"
      - "${WEBSERVER_PORT_SSL}:443"
    volumes:
      - ./:/var/www/app
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm: &app
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "${COMPOSE_PROJECT_NAME}-php"
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.6.4
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    environment:
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
#    volumes:
#      - "${DB_SRC}:/var/lib/mysql/"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
        - "1025:1025"  # SMTP
        - "8025:8025"  # Web UI
    networks:
        - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
